version: '2'
services:
  lounge:
    image: hashbang/chat
    container_name: lounge
    ports:
      - "9000:9000"
    expose:
      - "9000/tcp"
    volumes:
      - /home/lounge/data
    restart: always  
  proxy:
    #image: eforce21/letsencrypt-nginx-proxy:1.0.2
    #image: jwilder/nginx-proxy
    image: steveltn/https-portal
    container_name: proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    restart: always  
    depends_on:
      - "lounge"
    links:
      - "lounge"
    environment:
      DOMAINS: 'chat.hashbang.sh -> http://lounge:9000'
      STAGE: 'production'
